import {
    AdenCompat,
    _1977Compat,
    BrannanCompat,
    BrooklynCompat,
    ClarendonCompat,
    EarlybirdCompat,
    GinghamCompat,
    HudsonCompat,
    InkwellCompat,
    KelvinCompat,
    LarkCompat,
    LofiCompat,
    MavenCompat,
    MayfairCompat,
    MoonCompat,
    NashvilleCompat,
    PerpetuaCompat,
    ReyesCompat,
    RiseCompat,
    SlumberCompat,
    StinsonCompat,
    ToasterCompat,
    ValenciaCompat,
    WaldenCompat,
    WillowCompat,
    Xpro2Compat,
    Contrast,
  } from 'react-native-image-filter-kit'; 
  export const FILTERS = [
    {
      id: 1,
      title: 'Normal',
      filterComponent: AdenCompat,
    },

    {
      id: 2,
      title: 'Contrast',
      filterComponent: Contrast,
    },
    {
      id: 3,
      title: 'Mayfair',
      filterComponent: MayfairCompat,
    },
    {
      id: 4,
      title: 'Moon',
      filterComponent: MoonCompat,
    },
    {
      id: 5,
      title: 'Nashville',
      filterComponent: NashvilleCompat,
    },
    {
      id: 6,
      title: 'Perpetua',
      filterComponent: PerpetuaCompat,
    },
    {
      id: 7,
      title: 'Reyes',
      filterComponent: ReyesCompat,
    },
    {
      id: 8,
      title: 'Rise',
      filterComponent: RiseCompat,
    },
    {
      id: 9,
      title: 'Slumber',
      filterComponent: SlumberCompat,
    },
    {
      id: 10,
      title: 'Stinson',
      filterComponent: StinsonCompat,
    },
    {
      id: 11,
      title: 'Brooklyn',
      filterComponent: BrooklynCompat,
    },
    {
      id: 12,
      title: 'Earlybird',
      filterComponent: EarlybirdCompat,
    },
    {
      id: 13,
      title: 'Clarendon',
      filterComponent: ClarendonCompat,
    },
    {
      id: 14,
      title: 'Gingham',
      filterComponent: GinghamCompat,
    },
    {
      id: 15,
      title: 'Hudson',
      filterComponent: HudsonCompat,
    },
    {
      id: 16,
      title: 'Inkwell',
      filterComponent: InkwellCompat,
    },
    {
      id: 18,
      title: 'Kelvin',
      filterComponent: KelvinCompat,
    },
    {
      id: 19,
      title: 'Lark',
      filterComponent: LarkCompat,
    },
    {
      id: 20,
      title: 'Lofi',
      filterComponent: LofiCompat,
    },
    {
      id: 21,
      title: 'Toaster',
      filterComponent: ToasterCompat,
    },
    {
      id: 22,
      title: 'Valencia',
      filterComponent: ValenciaCompat,
    },
    {
      id: 23,
      title: 'Walden',
      filterComponent: WaldenCompat,
    },
    {
      id: 24,
      title: 'Willow',
      filterComponent: WillowCompat,
    },
    {id: 25,
      title: 'Xpro2',
      filterComponent: Xpro2Compat,
    },
    {
      id: 26,
      title: 'Aden',
      filterComponent: AdenCompat,
    },
    {
      id: 27,
      title: '_1977',
      filterComponent: _1977Compat,
    },
    {
      id: 28,
      title: 'Brannan',
      filterComponent: BrannanCompat,
    },
  ];